// File generated by FlutterFire CLI.
// Since I cannot run CLI, I am creating this shell.
// USER MUST OVERWRITE THIS with real config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnimplementedError('Android is not supported yet.');
      case TargetPlatform.iOS:
        throw UnimplementedError('iOS is not supported yet.');
      case TargetPlatform.macOS:
        throw UnimplementedError('macOS is not supported yet.');
      case TargetPlatform.windows:
        throw UnimplementedError('Windows is not supported yet.');
      case TargetPlatform.linux:
        throw UnimplementedError('Linux is not supported yet.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: 'REPLACE_WITH_YOUR_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    authDomain: 'REPLACE_WITH_YOUR_AUTH_DOMAIN',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
  );
}
